
package msg;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SMSServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SMSServiceSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "com.bos.utp.sm.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "com.bos.utp.sm.HelloWorldResponse")
    public String helloWorld();

    /**
     * �½������У�����
     * 
     * @param body
     * @param mobilephone
     * @param priority
     * @param systemName
     * @param appCode
     * @param userName
     * @param appPwd
     * @param loginName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SMSAdd", action = "http://tempuri.org/SMSAdd")
    @WebResult(name = "SMSAddResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SMSAdd", targetNamespace = "http://tempuri.org/", className = "com.bos.utp.sm.SMSAdd")
    @ResponseWrapper(localName = "SMSAddResponse", targetNamespace = "http://tempuri.org/", className = "com.bos.utp.sm.SMSAddResponse")
    public String smsAdd(
        @WebParam(name = "AppCode", targetNamespace = "http://tempuri.org/")
        String appCode,
        @WebParam(name = "AppPwd", targetNamespace = "http://tempuri.org/")
        String appPwd,
        @WebParam(name = "mobilephone", targetNamespace = "http://tempuri.org/")
        String mobilephone,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "Body", targetNamespace = "http://tempuri.org/")
        String body,
        @WebParam(name = "Priority", targetNamespace = "http://tempuri.org/")
        String priority,
        @WebParam(name = "SystemName", targetNamespace = "http://tempuri.org/")
        String systemName);

    /**
     * �����½������У����ţ����ŷָ����ֻ����
     * 
     * @param body
     * @param priority
     * @param systemName
     * @param appCode
     * @param userName
     * @param appPwd
     * @param loginName
     * @param mobilephones
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SMSAdds", action = "http://tempuri.org/SMSAdds")
    @WebResult(name = "SMSAddsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SMSAdds", targetNamespace = "http://tempuri.org/", className = "com.bos.utp.sm.SMSAdds")
    @ResponseWrapper(localName = "SMSAddsResponse", targetNamespace = "http://tempuri.org/", className = "com.bos.utp.sm.SMSAddsResponse")
    public String smsAdds(
        @WebParam(name = "AppCode", targetNamespace = "http://tempuri.org/")
        String appCode,
        @WebParam(name = "AppPwd", targetNamespace = "http://tempuri.org/")
        String appPwd,
        @WebParam(name = "mobilephones", targetNamespace = "http://tempuri.org/")
        String mobilephones,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "Body", targetNamespace = "http://tempuri.org/")
        String body,
        @WebParam(name = "Priority", targetNamespace = "http://tempuri.org/")
        String priority,
        @WebParam(name = "SystemName", targetNamespace = "http://tempuri.org/")
        String systemName);

}
