/**
 * 
 */
package com.goodcol.job;

import java.util.List;

import org.quartz.JobExecutionContext;

import com.goodcol.core.log.Logger;
import com.goodcol.plugin.activerecord.Db;
import com.goodcol.plugin.activerecord.Record;
import com.goodcol.util.DateTimeUtil;
import com.goodcol.util.ext.plugin.quartz.OuartzJob;

/**
 * @author
 * 
 */
public class PccmSyncOrgJob extends OuartzJob {

	public static Logger log = Logger.getLogger(PccmSyncOrgJob.class);

	// private static String dbLinkName = "@LK_DAP";
	/**
	 * 同步机构信息定时任务 2018年7月27日14:52:15
	 * 
	 * @author liutao
	 */
	@Override
	public void execute(JobExecutionContext arg0) {
		System.out.println("同步机构信息定时任务开始：" + DateTimeUtil.getTime());
		try {
			//String selectSql = "select * from A_DAP_DEPT_PARA_JS" + dbLinkName + " t where t.name is not null and t.id not like '002%'";
			String selectSql = "select * from A_DAP_DEPT_PARA_JS t where t.name is not null and t.id not like '002%'";
			List<Record> list = Db.use("default").find(selectSql);
			if (null != list && list.size() > 1) {
				String truncateSql = "truncate table SYS_ORG_INFO ";
				Db.use("default").update(truncateSql);
				String sql = "insert into SYS_ORG_INFO (id,orgname,orgnum,UPID,ORDERNUM,ORGADRESS,STAT,BY2,BY3,BY5,BANCSID) "
						+ " select t.id,t.name,t.id,t.up_dept,'000',t.name, "
						+ " '1',t.deptlevel + 1,'',t.upup_dept||','||t.up_dept,t.br_no "
//						+ " from A_DAP_DEPT_PARA_JS" + dbLinkName + " t "
						+ " from A_DAP_DEPT_PARA_JS t "
						+ " where t.name is not null "
//						+ " and t.name not like '%苏州%' "
//						+ " and t.name not like '%党委%'"
//						+ " and t.name not like '%清算%'"
//						+ " and t.name not like '%不计明细%'"
//						+ " and t.name not like '%工会%'"
//						+ " and t.name not like '%银行卡%'"
//						+ " and t.name not like '%记账式国债%'"
//						+ " and t.name not like '%理财%'"
//						+ " and t.name not like '%保卫科%'"
//						+ " and t.name not like '%信用卡%'"
//						+ " and t.name not like '%虚拟%'"
//						+ " and t.name not like '%人秘科%'"
//						+ " and t.name not like '%库房%'"
//						+ " and t.name not like '%金库%'"
//						+ " and t.name not like '%行长室%'"
//						+ " and t.name not like '%办公室%'"
//						+ " and t.name not like '%人员%'"
//						+ " and t.name not like '%其他%'"
//						+ " and t.name not like '%扬州分行本部%'"
//						+ " and t.name not like '%扬州分行国际结算部%'"
//						+ " and t.name not like '%扬州分行风险管理部%'"
//						+ " and t.name not like '%扬州法律与合规部%'"
//						+ " and t.name not like '%扬州分行监察部%'"
//						+ " and t.name not like '%扬州分行个人金融部%'"
//						+ " and t.name not like '%扬州分行保卫部%'"
//						+ " and t.name not like '%扬州分行公司业务部%'"
//						+ " and t.name not like '%扬州分行信息科技部%'"
//						+ " and t.name not like '%扬州分行人力资源部%'"
//						+ " and t.name not like '%扬州分行运营部%'"
//						+ " and t.name not like '%扬州分行党务工作部%'"
//						+ " and t.name not like '%扬州分行中小企业业务中心%'"
//						+ " and t.name not like '%扬州分行法律与合规部%'"
//						+ " and t.name not like '%扬州财务管理部%'"
//						+ " and t.name not like '%扬州财富管理与私人银行中心%'"
//						+ " and t.name not like '%淮安分行本部%'"
//						+ " and t.name not like '%淮安分行法律与合规部%'"
//						+ " and t.name not like '%淮安分行贸易金融部%'"
//						+ " and t.name not like '%淮安分行个人金融部%'"
//						+ " and t.name not like '%淮安分行中小企业业务中心%'"
//						+ " and t.name not like '%淮安分行党务工作部%'"
//						+ " and t.name not like '%淮安分行监察保卫部%'"
//						+ " and t.name not like '%淮安分行人力资源部%'"
//						+ " and t.name not like '%淮安分行财务管理部%'"
//						+ " and t.name not like '%淮安分行风险管理部%'"
//						+ " and t.name not like '%淮安分行运营部%'"
//						+ " and t.name not like '%淮安财富管理与私人银行中心%'"
//						+ " and t.name not like '%淮安分行公司业务部%'"
//						+ " and t.name not like '%镇江分行本部%'"
//						+ " and t.name not like '%镇江分行保卫部%'"
//						+ " and t.name not like '%镇江分行法律与合规部%'"
//						+ " and t.name not like '%镇江分行信息科技部%'"
//						+ " and t.name not like '%镇江分行监察部%'"
//						+ " and t.name not like '%镇江分行风险管理部%'"
//						+ " and t.name not like '%镇江分行法律合规部%'"
//						+ " and t.name not like '%镇江分行个人金融部%'"
//						+ " and t.name not like '%镇江记帐式国债%'"
//						+ " and t.name not like '%镇江分行公司业务部%'"
//						+ " and t.name not like '%镇江内退%'"
//						+ " and t.name not like '%镇江分行授信执行部%'"
//						+ " and t.name not like '%镇江分行运营部%'"
//						+ " and t.name not like '%镇江分行国际结算部%'"
//						+ " and t.name not like '%镇江离退休%'"
//						+ " and t.name not like '%镇江分行财务管理部%'"
//						+ " and t.name not like '%镇江分行人力资源部%'"
//						+ " and t.name not like '%镇江分行中小企业业务中心%'"
//						+ " and t.name not like '%镇江分行财富管理与私人银行中心%'"
//						+ " and t.name not like '%盐城分行本部%'"
//						+ " and t.name not like '%盐城分行公共部门%'"
//						+ " and t.name not like '%盐城分行国际结算部%'"
//						+ " and t.name not like '%盐城分行党务工作部%'"
//						+ " and t.name not like '%盐城分行保全部%'"
//						+ " and t.name not like '%盐城分行科技部%'"
//						+ " and t.name not like '%盐城分行个人金融部%'"
//						+ " and t.name not like '%盐城分行运营部%'"
//						+ " and t.name not like '%盐城分行人力资源部%'"
//						+ " and t.name not like '%盐城分行承兑汇票专用%'"
//						+ " and t.name not like '%盐城分行公司业务部%'"
//						+ " and t.name not like '%盐城分行中小企业中心%'"
//						+ " and t.name not like '%盐城分行监察保卫部%'"
//						+ " and t.name not like '%盐城分行财务管理部%'"
//						+ " and t.name not like '%中国银行盐城分行内控与法律合规部%'"
//						+ " and t.name not like '%无锡分行本部%'"
//						+ " and t.name not like '%无锡分行中小企业业务中心%'"
//						+ " and t.name not like '%无锡分行公司业务营销一中心%'"
//						+ " and t.name not like '%无锡分行党务工作部%'"
//						+ " and t.name not like '%无锡分行监察部%'"
//						+ " and t.name not like '%无锡分行私人银行中心%'"
//						+ " and t.name not like '%无锡分行公司业务营销三中心%'"
//						+ " and t.name not like '%无锡分行财务管理部%'"
//						+ " and t.name not like '%无锡分行授信执行部%'"
//						+ " and t.name not like '%无锡分行法律合规部%'"
//						+ " and t.name not like '%无锡分行人力资源部%'"
//						+ " and t.name not like '%无锡分行公司业务营销二中心%'"
//						+ " and t.name not like '%无锡分行运营部%'"
//						+ " and t.name not like '%无锡分行个人金融部%'"
//						+ " and t.name not like '%无锡分行风险管理部%'"
//						+ " and t.name not like '%无锡分行信息科技部%'"
//						+ " and t.name not like '%无锡分行直属支行管理总部%'"
//						+ " and t.name not like '%无锡分行公司业务部%'"
//						+ " and t.name not like '%无锡分行国际结算部%'"
//						+ " and t.name not like '%无锡分行保卫部%'"
//						+ " and t.name not like '%无锡分行监察保卫部%'"
//						+ " and t.name not like '%国内结算与现金管理部%' 　"
//						+ " and t.name not like '%省行法律合规部%'"
//						+ " and t.name not like '%省行风险管理部%'"
//						+ " and t.name not like '%省行党务工作部%'"
//						+ " and t.name not like '%省行风险管理部第二授信评审中心%'"
//						+ " and t.name not like '%省行风险管理部第一授信评审中心%'"
//						+ " and t.name not like '%省行离退休%'"
//						+ " and t.name not like '%省行监察部%'"
//						+ " and t.name not like '%省行授信执行部%'"
//						+ " and t.name not like '%省行稽核部%'"
//						+ " and t.name not like '%省行财务管理部%'"
//						+ " and t.name not like '%营运中心%'"
//						+ " and t.name not like '%省行人力资源部%'"
//						+ " and t.name not like '%省行培训中心%'"
//						+ " and t.name not like '%省行运营控制部%'"
//						+ " and t.name not like '%省行风险管理部第三授信评审中心%'"
//						+ " and t.name not like '%渠道管理与网络金融部%'"
//						+ " and t.name not like '%省行总务部%'"
//						+ " and t.name not like '%江苏省分行南京管理部%'"
//						+ " and t.name not like '%省行信息科技部%'"
//						+ " and t.name not like '%省行保卫部%'"
//						+ " and t.name not like '%徐州分行本部%'"
//						+ " and t.name not like '%徐州分行公司业务部%'"
//						+ " and t.name not like '%徐州分行党务工作部%'"
//						+ " and t.name not like '%徐州分行个人金融部%'"
//						+ " and t.name not like '%徐州分行信息科技部%'"
//						+ " and t.name not like '%徐州分行国际结算部%'"
//						+ " and t.name not like '%徐州分行监察部%'"
//						+ " and t.name not like '%徐州分行监察室%'"
//						+ " and t.name not like '%徐州分行人事教育部%'"
//						+ " and t.name not like '%徐州分行风险管理部%'"
//						+ " and t.name not like '%徐州分行中小企业业务中心%'"
//						+ " and t.name not like '%徐州分行保卫部%'"
//						+ " and t.name not like '%徐州分行财务管理部%'"
//						+ " and t.name not like '%徐州分行调研室%'"
//						+ " and t.name not like '%徐州分行法律与合规部%'"
//						+ " and t.name not like '%徐州分行市行票据中心%'"
//						+ " and t.name not like '%徐州分行稽核%'"
//						+ " and t.name not like '%徐州分行运营部%'"
//						+ " and t.name not like '%连云港分行本部%'"
//						+ " and t.name not like '%连云港分行风险管理部%'"
//						+ " and t.name not like '%连云港分行运营部%'"
//						+ " and t.name not like '%连云港分行法律与合规部%'"
//						+ " and t.name not like '%连云港分行监察室%'"
//						+ " and t.name not like '%连云港分行财富管理与私人银行中心%'"
//						+ " and t.name not like '%连云港分行零售部消费信贷%'"
//						+ " and t.name not like '%连云港分行党务工作部%'"
//						+ " and t.name not like '%连云港分行人事教育部%'"
//						+ " and t.name not like '%连云港财务管理部%'"
//						+ " and t.name not like '%连云港公司业务部%'"
//						+ " and t.name not like '%连云港个人金融部%'"
//						+ " and t.name not like '%连云港分行中小企业业务中心%'"
//						+ " and t.name not like '%连云港国际结算部%'"
//						+ " and t.name not like '%泰州分行本部%'"
//						+ " and t.name not like '%泰州新区支行（银票）%'"
//						+ " and t.name not like '%泰州高港支行（银票）%'"
//						+ " and t.name not like '%泰州海陵支行（银票）%'"
//						+ " and t.name not like '%泰州分行保卫部%'"
//						+ " and t.name not like '%泰州分行信息科技部%'"
//						+ " and t.name not like '%泰州劝业支行（银票）%'"
//						+ " and t.name not like '%泰州分行个人金融部%'"
//						+ " and t.name not like '%中国银行泰州分行内控与法律合规部%'"
//						+ " and t.name not like '%姜堰支行（银票）%'"
//						+ " and t.name not like '%泰州分行公司业务部%'"
//						+ " and t.name not like '%泰州分行风险管理部%'"
//						+ " and t.name not like '%泰州中小企业部%'"
//						+ " and t.name not like '%靖江支行（银票）%'"
//						+ " and t.name not like '%泰州分行监察保卫部%'"
//						+ " and t.name not like '%兴化支行（银票）%'"
//						+ " and t.name not like '%泰州分行法律与合规部%'"
//						+ " and t.name not like '%泰州分行人力资源部%'"
//						+ " and t.name not like '%泰州分行运营部%'"
//						+ " and t.name not like '%泰兴支行（银票）%'"
//						+ " and t.name not like '%泰州分行国际结算部%'"
//						+ " and t.name not like '%泰州分行财务管理部%'"
//						+ " and t.name not like '%泰州分行资产保全部%'"
//						+ " and t.name not like '%宿迁分行本部%'"
//						+ " and t.name not like '%宿迁分行财务管理部%'"
//						+ " and t.name not like '%宿迁分行监察部%'"
//						+ " and t.name not like '%宿迁分行财富管理与私人银行中心%'"
//						+ " and t.name not like '%宿迁分行法律与合规部%'"
//						+ " and t.name not like '%宿迁分行公司部%'"
//						+ " and t.name not like '%宿迁分行运营部%'"
//						+ " and t.name not like '%宿迁分行综合部%'"
//						+ " and t.name not like '%宿迁分行个金部%'"
//						+ " and t.name not like '%宿迁分行国际结算部%'"
//						+ " and t.name not like '%宿迁分行风险管理部%'"
//						+ " and t.name not like '%宿迁分行网点管理中心%'"
//						+ " and t.name not like '%宿迁分行中小企业业务中心%'"
//						+ " and t.name not like '%常州分行本部%'"
//						+ " and t.name not like '%常州分行授信执行部%'"
//						+ " and t.name not like '%常州分行财务管理部%'"
//						+ " and t.name not like '%常州分行法律与合规部%'"
//						+ " and t.name not like '%常州分行人力资源部2%'"
//						+ " and t.name not like '%常州分行人力资源部%'"
//						+ " and t.name not like '%常州分行运营部%'"
//						+ " and t.name not like '%常州分行贸易金融部%'"
//						+ " and t.name not like '%常州分行风险管理部%'"
//						+ " and t.name not like '%常州分行消费信贷中心%'"
//						+ " and t.name not like '%常州分行个人金融部%'"
//						+ " and t.name not like '%常州分行党务工作部%'"
//						+ " and t.name not like '%常州分行公司金融部%'"
//						+ " and t.name not like '%常州分行信息科技部%'"
//						+ " and t.name not like '%常州分行保卫部%'"
//						+ " and t.name not like '%常州分行总务部2%'"
//						+ " and t.name not like '%常州分行总务部1%'"
//						+ " and t.name not like '%常州分行财富管理中心%'"
//						+ " and t.name not like '%常州分行监察部%'"
//						+ " and t.name not like '%常州分行中小企业业务中心%'"
//						+ " and t.name not like '%南通分行本部%'"
//						+ " and t.name not like '%南通资金计划处%'"
//						+ " and t.name not like '%南通分行个人金融部%'"
//						+ " and t.name not like '%南通公司业务部%'"
//						+ " and t.name not like '%南通分行保卫部%'"
//						+ " and t.name not like '%南通总务部%'"
//						+ " and t.name not like '%南通授信执行部%'"
//						+ " and t.name not like '%南通分行财务管理部%'"
//						+ " and t.name not like '%南通分行党务工作部%'"
//						+ " and t.name not like '%南通分行私人银行中心%'"
//						+ " and t.name not like '%南通人力资源部%'"
//						+ " and t.name not like '%南通保卫部%'"
//						+ " and t.name not like '%南通分行中小企业业务中心%' 　"
//						+ " and t.name not like '%南通分行监察部%'"
//						+ " and t.name not like '%南通分行信息科技部%'"
//						+ " and t.name not like '%南通分行风险管理部%'"
//						+ " and t.name not like '%南通法律与合规部%'"
//						+ " and t.name not like '%南通国际结算部%'"
//						+ " and t.name not like '%财会%'"
//						+ " and t.name not like '%保卫%'"
//						+ " and t.name not like '%基金%'"
//						+ " and t.name not like '%国债%'"
//						+ " and t.name not like '%公共部门%'"
//						+ " and t.name not like '%储蓄%'"
//						+ " and t.name not like '%会计%'"
//						+ " and t.name not like '%盐城开放式资金%'"
//						+ " and t.name not like '%盐城分行东台支行基建办%'"
//						+ " and t.name not like '%无锡江阴支行卡部%'"
//						+ " and t.name not like '%无锡分行江阴支行监察部%'"
//						+ " and t.name not like '%无锡锡山支行行部%'"
//						+ " and t.name not like '%无锡分行宜兴支行监察部%'"
//						+ " and t.name not like '%南京地区溧水支行开放式资金%'"
//						+ " and t.name not like '%江浦%'"
//						+ " and t.name not like '%连云港灌南支行卡部%'"
//						+ " and t.name not like '%连云港核电支行存款科%'"
//						+ " and t.name not like '%连云港核电支行信贷科%'"
//						+ " and t.name not like '%泰州靖江支行营业部专柜%'"
//						+ " and t.name not like '%泰州海陵支行业务发展部(原)%'"
//						+ " and t.name not like '%泰州海陵支行综合管理部(原)%'"
//						+ " and t.name not like '%泰州国际结算部门%'"
//						+ " and t.name not like '%常州武进国际结算部%'"
//						+ " and t.name not like '%常州武进计财部%'"
//						+ " and t.name not like '%中国银行常州武进支行监察部%'"
//						+ " and t.name not like '%常州溧阳国际结算%'"
//						+ " and t.name not like '%南通通州国际结算部%'"
//						+ " and t.name not like '%南通通州资金计划部%'"
//						+ " and t.name not like '%南通如皋国际结算部%'"
//						+ " and t.name not like '%南通如皋资金计划处%'"
//						+ " and t.name not like '%南通如东资金计划处%'"
//						+ " and t.name not like '%南通如东收付系统柜组%'"
//						+ " and t.name not like '%南通如东国际结算部%'"
//						+ " and t.name not like '%南通海安客户经理%'"
//						+ " and t.name not like '%南通海安国际结算部%'"
//						+ " and t.name not like '%南通海安人行对转账%'"
//						+ " and t.name not like '%南通海安电脑部%'"
//						+ " and t.name not like '%南通启东重要空白凭证库%'"
//						+ " and t.name not like '%南通启东国际结算部%'"
//						+ " and t.name not like '%南通崇川支行国贸%'"
//						+ " and t.name not like '%扬州仪征支行国际结算%'"
//						+ " and t.name not like '%扬州宝应支行国际结算部%'"
//						+ " and t.name not like '%盐城东台支行国际结算%'"
//						+ " and t.name not like '%无锡惠山支行国际结算%'"
//						+ " and t.name not like '%无锡惠山支行风险管理%'"
//						+ " and t.name not like '%中国银行无锡分行江阴支行风险管理部%'"
//						+ " and t.name not like '%无锡江阴支行国际结算部%'"
//						+ " and t.name not like '%无锡锡山支行国际结算部%'"
//						+ " and t.name not like '%中国银行无锡分行宜兴支行风险管理部%'"
//						+ " and t.name not like '%无锡宜兴支行国际结算%'"
//						+ " and t.name not like '%无锡新区支行国际结算部%'"
//						+ " and t.name not like '%泰州靖江支行国际结算部%'"
//						+ " and t.name not like '%常州武进风险管理部%'"
//						+ " and t.name not like '%常州金坛支行国际结算%'"
//						+ " and t.name not like '%常州金坛支行风险管理部%'"
//						+ " and t.name not like '%南京地区萨家湾支行萨办%'"
//						+ " and t.name not like '%无锡锡山支行业管（风险）%'"
//						+ " and t.name not like '%无锡分行惠山支行综合管理部%'"
//						+ " and t.name not like '%南通营业部%'"
//						+ " and t.name not like '%南通港闸支行国贸%'"
//						+ " and t.name not like '%南通海门国际结算部%'"
//						+ " and t.name not like '%南通通州国贸%'"
//						+ " and t.name not like '%南通如东国贸%'"
//						+ " and t.name not like '%南通城东国贸%'"
//						+ " and t.name not like '%宿迁泗阳支行管理部%'"
//						+ " and t.name not like '%盐城大丰支行国际结算部%'"
//						+ " and t.name not like '%盐城城南支行营业部%'"
						+ " and t.id not like '002%'";
				Db.use("default").update(sql);

				// 循环设置机构所有父级路径 2018年8月10日10:57:56 ---liutao
				// 首先查询最小层级的机构
				sql = "update sys_org_info set by5 = ('000000000,'||by5) where by2 = '4'";
				Db.use("default").update(sql);
				sql = "update sys_org_info set by5 = substr(by5,2,9) where by2 = '2'";
				Db.use("default").update(sql);
			}
			success();
		} catch (Exception e) {
			error();
			log.error("同步机构信息定时任务执行失败：" + e);
		}
		
		System.out.println("同步机构信息定时任务结束：" + DateTimeUtil.getTime());
	}
}
