package com.goodcol.model;

import com.goodcol.core.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("sys_position", "id", SysPosition.class);
		arp.addMapping("oa_leave", "id", OaLeave.class);
		arp.addMapping("pccm_kpi_param", GcmsKpIPara.class);
	}
}

