package com.goodcol.ftp;

public enum FtpDownloadStatus {
	DOWNLOAD_SUCC_NEW,			
	DOWNLOAD_FAIL_NEW,			
	DOWNLOAD_FAIL_TIMEOUT_NEW,
	DOWNLOAD_FAIL_IOEXCEPTION_NEW,
	DOWNLOAD_SUCC_BREAK,	 	
	DOWNLOAD_FAIL_BREAK,	
	DOWNLOAD_FAIL_TIMEOUT_BREAK,
	DOWNLOAD_FAIL_IOEXCEPTION_BREAK,
	DOWNLOAD_REMOTE_FILE_NOT_EXIST,
	DOWNLOAD_LOCAL_FILE_CREATE_FAIL, 	
	DOWNLOAD_FILE_DOWNLOADED,
	DOWNLOAD_CLOSEREMOTESTREAM_ERROR,
	DOWNLOAD_CLOSELOCALSTREAM_ERROR,
	DOWNLOAD_UNKNOWN		
}
