package com.goodcol.ftp;

public enum FtpUploadStatus {
	UPLOAD_SUCC_NEW,			
	UPLOAD_FAIL_NEW,			
	UPLOAD_FAIL_TIMEOUT_NEW,
	UPLOAD_FAIL_IOEXCEPTION_NEW,
	UPLOAD_SUCC_BREAK,		
	UPLOAD_FAIL_BREAK,		
	UPLOAD_FAIL_TIMEOUT_BREAK,
	UPLOAD_FAIL_IOEXCEPTION_BREAK,
	UPLOAD_LOCAL_FILE_NOT_EXIST,
	UPLOAD_INVALID_REMOTE_FILE_NAME,
	UPLOAD_REMOTE_DIR_CREATE_FAIL,	
	UPLOAD_FILE_UPLOADED,		
	UPLOAD_CLOSEREMOTESTREAM_ERROR,
	UPLOAD_CLOSELOCALSTREAM_ERROR,
	UPLOAD_CONNECTION_ERR,
	UPLOAD_NO_DCS_SET,
	UPLOAD_UNKNOWN				
}
